name: GitHub Actions Demo
on: [push]
jobs: 
  Builds:
    runs-on: Ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ." 

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:" 
          tree

