name: GitHub Actions Demo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "type in environment"
        type: environment
        required: true
jobs: 
  Builds:
    runs-on: Ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ." 

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:" 
          tree
  Test:
    runs-on: Ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [Builds]
    environment: Test
    steps:
      - name: echo "🧪 Testing..."
        run: echo "🧪 Testing..."
  Load-Test:
    runs-on: Ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [Builds]
    environment: Load-Test
    steps:
      - run: |
          echo "🧪 Testing..."
          sleep 15

  Production:
    runs-on: Ubuntu-latest
    needs: [Test,Load-Test]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: echo step 1..5
