name: GitHub Actions Demo
on: [push]
jobs: 
  Builds:
    runs-on: Ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ." 
