name: Reuse other workflow
on: [workflow_dispatch]
jobs:
  call-workflow:
     uses: ./.github/workflows/reusable.yml 
     with:
       who-to-greet: '@octocat'
  use-output:
     runs-on: Ubuntu-latest 
     steps:
       - run: echo ${{needs.call-workflow.outputs.current-time}}
